import { Inter } from "next/font/google";
import '/app/styles/index.css'
import _NavigationBar from "@/app/(components)/_NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "dhir0hit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <_NavigationBar/>
        {children}
      </body>
    </html>
  );
}
